name: "Run a script in a Node.js environment"
description: "Checkout code, set up Node, install packages and run the specified script"
inputs:
  script:
    description: "The script to run"
    required: true
  node-version:
    description: "Node version to set up. The system version is used if not specified."
    required: false
  package-manager:
    description: "The package manager to use - npm or yarn"
    required: false
    default: npm
  working-directory:
    description: "The working directory to use"
    required: false
runs:
  using: composite
  steps:
    - name: Pull repository
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        PKG_MGR: ${{ inputs.package-manager }}
      run: |
        [[ $PKG_MGR == npm ]] && npm ci --include-workspace-root || yarn install --frozen-lockfile

    - name: Run script
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        COMMAND: ${{ inputs.script }}
      run: eval "$COMMAND"
