name: "Run Checkov"
description: "Run Checkov and report results to the job summary if there are failing checks"
inputs:
  config-file:
    description: "Path to a Checkov configuration file"
    required: false
  path:
    description: "Only run checks on files matching the specified path filter"
    required: false
  pull-repository:
    description: "Pull the repository before running Checkov"
    required: false
    default: "true"
  skip-checks:
    description: "Checks to skip. Multiple values separated by commas, spaces or newlines"
    required: false
  skip-frameworks:
    description: "Frameworks to skip. Multiple values separated by commas, spaces or newlines"
    required: false
runs:
  using: composite
  steps:
    - name: Check if merge commit
      id: check-merge-commit
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
      run: |
        merging=false
        [[ $EVENT == pull_request ]] && merging=true && fetch_depth=2
        echo "fetch-depth=${fetch_depth:-}" >> "$GITHUB_OUTPUT"
        echo "merging=$merging" >> "$GITHUB_OUTPUT"

    - name: Pull repository
      if: ${{ inputs.pull-repository == 'true' }}
      uses: actions/checkout@v7
      with:
        fetch-depth: ${{ steps.check-merge-commit.outputs.fetch-depth }}

    - name: Parse options
      id: checkov-options
      shell: bash
      env:
        SKIP_CHECKS: ${{ inputs.skip-checks }}
        SKIP_FRAMEWORKS: ${{ inputs.skip-frameworks }}
      run: |
        if [[ -n $SKIP_CHECKS ]]; then
          echo "skip-checks=$(xargs <<< "$SKIP_CHECKS" | tr ' ' ',')" >> "$GITHUB_OUTPUT"
        fi

        if [[ -n $SKIP_FRAMEWORKS ]]; then
          echo "skip-frameworks=$(xargs <<< "$SKIP_FRAMEWORKS" | tr ' ' ',')" >> "$GITHUB_OUTPUT"
        fi

    - name: Get pull request files
      id: get-pr-files
      if: ${{ steps.check-merge-commit.outputs.merging == 'true' }}
      shell: bash
      env:
        DIR: ${{ inputs.path }}
      run: |
        files=$(git diff --name-only --diff-filter=d HEAD^...HEAD)

        if [[ $DIR ]]; then
          files=$(grep -E --regexp="^.*\/${DIR}\/.*$" <<< "$files") ||
            case $? in 1) echo "No files to check" && exit 0 ;; *) exit $? ;; esac
        fi

        # The official action expects a comma-separated list for the `file` input
        echo "files=$(xargs <<< "$files" | tr ' ' ',')" >> "$GITHUB_OUTPUT"

    - name: Run Checkov on a pull request
      uses: bridgecrewio/checkov-action@v12
      if: ${{ steps.check-merge-commit.outputs.merging == 'true' && steps.get-pr-files.outputs.files != '' }}
      with:
        config_file: ${{ inputs.config-file }}
        file: ${{ steps.get-pr-files.outputs.files }}
        output_file_path: ${{ runner.temp }}/checkov/pr_results.sarif
        output_format: cli,sarif
        quiet: true
        skip_check: ${{ steps.checkov-options.outputs.skip-checks }}
        skip_framework: ${{ steps.checkov-options.outputs.skip-frameworks }}

    - name: Run Checkov on a directory
      uses: bridgecrewio/checkov-action@v12
      if: ${{ steps.check-merge-commit.outputs.merging == 'false' && inputs.path != '' }}
      with:
        config_file: ${{ inputs.config-file }}
        directory: ${{ inputs.path }}
        output_file_path: ${{ runner.temp }}/checkov/directory_results.sarif
        output_format: cli,sarif
        quiet: true
        skip_check: ${{ steps.checkov-options.outputs.skip-checks }}
        skip_framework: ${{ steps.checkov-options.outputs.skip-frameworks }}

    - name: Run Checkov on the repo
      uses: bridgecrewio/checkov-action@v12
      if: ${{ steps.check-merge-commit.outputs.merging == 'false' && inputs.path == '' }}
      with:
        config_file: ${{ inputs.config-file }}
        directory: .
        output_file_path: ${{ runner.temp }}/checkov/repo_results.sarif
        output_format: cli,sarif
        quiet: true
        skip_check: ${{ steps.checkov-options.outputs.skip-checks }}
        skip_framework: ${{ steps.checkov-options.outputs.skip-frameworks }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v4
      if: ${{ success() || failure() }}
      with:
        sarif_file: ${{ runner.temp }}/checkov

    - name: Report Checkov result
      if: ${{ failure() }}
      shell: bash
      env:
        REPORT: ${{ github.action_path }}/../../scripts/report-step-result/print-file.sh
        FILE: ${{ runner.temp }}/checkov/formatted_results.txt
        CODE_BLOCK: "true"
      run: $REPORT >> "$GITHUB_STEP_SUMMARY"
