version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["**/*"]
    schedule:
      interval: weekly
    target-branch: main
    labels: [dependabot]
    commit-message:
      prefix: DEP
