name: "Install Node.js packages"
description: "Checkout code, set up Node and install packages"
inputs:
  node-version:
    description: "Node version to set up. The system version is used if not specified."
    required: false
  package-manager:
    description: "The package manager to use - npm or yarn"
    required: false
    default: npm
runs:
  using: composite
  steps:
    - name: Pull repository
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: Install dependencies
      shell: bash
      env:
        PKG_MGR: ${{ inputs.package-manager }}
      run: |
        [[ $PKG_MGR == npm ]] && npm ci || yarn install --frozen-lockfile
