name: "Run pre-commit"
description: "Run pre-commit and report results to the job summary if there are failing hooks"
inputs:
  all-files:
    description: "Run hooks on all files in the repo when running on a PR; default behaviour when running on a branch"
    required: false
    default: "false"
  install-dependencies:
    description: "Install dev packages from package.json - this is needed for hooks which have dependencies"
    required: false
    default: "false"
  package-manager:
    description: "The package manager to use to install dependencies - npm or yarn"
    required: false
    default: npm
  pull-repository:
    description: "Pull the repository before running pre-commit"
    required: false
    default: "true"
  args:
    description: "Extra arguments to pass to the pre-commit program"
    required: false
runs:
  using: composite
  steps:
    - name: Check if merge commit
      id: check-merge-commit
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
        ALL_FILES: ${{ inputs.all-files == 'true' }}
      run: |
        if [[ $EVENT == pull_request ]]; then
          $ALL_FILES || files="--from-ref HEAD^ --to-ref HEAD"
          fetch_depth=2
        fi
        
        echo "fetch-depth=${fetch_depth:-}" >> "$GITHUB_OUTPUT"
        echo "files=${files:---all-files}" >> "$GITHUB_OUTPUT"

    - name: Pull repository
      if: ${{ inputs.pull-repository == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ steps.check-merge-commit.outputs.fetch-depth }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache-dependency-path: ./.github/workflows
        cache: pip

    - name: Set up Node
      if: ${{ inputs.install-dependencies == 'true' }}
      uses: actions/setup-node@v4
      with:
        cache: ${{ inputs.package-manager }}

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      env:
        PKG_MGR: ${{ inputs.package-manager }}
      run: |
        [[ $PKG_MGR == npm ]] && npm ci || yarn install --frozen-lockfile

    - name: Install pre-commit
      run: echo "::group::pip output" && pip install pre-commit && echo "::endgroup::"
      shell: bash

    - name: Cache pre-commit dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-pre-commit-${{ github.head_ref || github.ref_name }}
        restore-keys: ${{ runner.os }}-pre-commit-
        path: ~/.cache/pre-commit

    - name: Run pre-commit
      shell: bash
      env:
        ARGS: ${{ steps.check-merge-commit.outputs.files }} ${{ inputs.args }}
        OUTPUT_FILE: ${{ runner.temp }}/pre-commit.output
      run: |
        read -ra args < <(xargs <<< "$ARGS")
        pre-commit run --show-diff-on-failure --color=always "${args[@]}" ||
          (git restore . && pre-commit run --show-diff-on-failure --color=never "${args[@]}" >> "$OUTPUT_FILE")

    - name: Report pre-commit result
      if: ${{ failure() }}
      shell: bash
      env:
        REPORT: ${{ github.action_path }}/../../scripts/report-step-result/print-file.sh
        FILE: ${{ runner.temp }}/pre-commit.output
        CODE_BLOCK: "true"
      run: $REPORT >> "$GITHUB_STEP_SUMMARY"
