name: "Run a SonarCloud scan"
description: "Run a SonarCloud scan on the repo and report results to the SonarCloud server"
inputs:
  args:
    description: "Additional arguments to the sonarcloud scanner"
    required: false
  projectBaseDir:
    description: "Set the sonar.projectBaseDir analysis property"
    required: false
    default: ${{ github.workspace }}
  coverage-artifact:
    description: "Name of the artifact containing the coverage report (lcov.info file)"
    required: false
    default: coverage
  coverage-run-id:
    description: "ID of the workflow run that produces the coverage report"
    required: false
  coverage-location:
    description: "The directory where SonarCloud expects to find the coverage report (specified in the config file)"
    required: false
    default: coverage
  github-token:
    description: "The token to authenticate to the GitHub API - the value of secrets.GITHUB_TOKEN"
    required: true
  sonar-token:
    description: "The token to authenticate access to SonarCloud"
    required: true
  pull-repository:
    description: "Pull the repository before running the scan"
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Pull repository
      if: ${{ inputs.pull-repository == 'true' }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Await coverage report
      if: ${{ inputs.coverage-artifact != null && inputs.coverage-run-id == null }}
      id: coverage
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ARTIFACT_NAME: ${{ inputs.coverage-artifact }}
      run: ${{ github.action_path }}/../../scripts/gha/await-artifact.sh

    - name: Get coverage results
      if: ${{ inputs.coverage-artifact != null }}
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ${{ inputs.coverage-artifact }}
        path: ${{ inputs.coverage-location }}
        run-id: ${{ steps.coverage.outputs.run-id }}
        github-token: ${{ (steps.coverage.outputs.run-id || github.run_id) != github.run_id && inputs.github-token || null }}

    - name: Scan
      uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1
      with:
        args: ${{ inputs.args }}
        projectBaseDir: ${{ inputs.projectBaseDir }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
