name: "Send a Workflow Slack Notification"
description: "Sends a notification to a Slack channel"
inputs:
  aws-role-arn:
    description: "ARN of AWS role to assume when sending SNS messages"
    required: false
  aws-region:
    description: "AWS region to use"
    required: false
    default: eu-west-2
  sns-topic-arn:
    description: "SNS Topic ARN to publish the notification to"
    required: true
  message-title:
    description: "Title of the message to send"
    required: false
  message-description:
    description: "Description/body of the message to send"
    required: false
  status:
    description: "Optional status to include in the message (e.g., 'Success', 'Failure')"
    required: false
  status-icon:
    description: "Optional icon to include with the status (e.g., ':white_check_mark:', ':x:')"
    required: false
runs:
  using: composite
  steps:
    - name: Assume AWS Role
      if: ${{ inputs.aws-role-arn != null }}
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Slack notification
      id: slack-notification
      shell: bash
      env:
        SNS_TOPIC_ARN: ${{ inputs.sns-topic-arn }}
        MESSAGE_TITLE: ${{ inputs.message-title }}
        MESSAGE_DESCRIPTION: ${{ inputs.message-description }}
        STATUS: ${{ inputs.status }}
        STATUS_ICON: ${{ inputs.status-icon }}
        WORKFLOW_MESSAGE: true
      run: |
        echo ${{ github.action_path }}
        ${{ github.action_path }}/../scripts/slack-notification.sh
