name: "Send a Workflow Slack Notification"
description: "Sends a notification to a Slack channel"
inputs:
  sns-topic-arn:
    description: "SNS Topic ARN to publish the notification to"
    required: true
  message-title:
    description: "Title of the message to send"
    required: false
  message-description:
    description: "Description/body of the message to send"
    required: false
  status:
    description: "Optional status to include in the message (e.g., 'Success', 'Failure')"
    required: false
  status-icon:
    description: "Optional icon to include with the status (e.g., ':white_check_mark:', ':x:')"
    required: false
runs:
  using: composite
  steps:
    - name: Slack notification
      id: slack-notification
      shell: bash
      env:
        SNS_TOPIC_ARN: ${{ inputs.sns-topic-arn }}
        MESSAGE_TITLE: ${{ inputs.message-title }}
        MESSAGE_DESCRIPTION: ${{ inputs.message-description }}
        STATUS: ${{ inputs.status }}
        STATUS_ICON: ${{ inputs.status-icon }}
        WORKFLOW_MESSAGE: true
      run: |
        echo ${{ github.action_path }}
        ${{ github.action_path }}/../scripts/slack-notification.sh
