name: Validate SAM template schema test

on: pull_request
permissions: {}

concurrency:
  group: test-validate-template-schema-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v6

      - name: Validate with resource checks
        uses: ./sam/validate-template-schema
        with:
          template: deploy/template.yml
          container-port: "5090"
          expected-resources: |
            ["LoadBalancer","EcsCluster","SessionsTable","ECSServiceTaskDefinition"]
